
TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES( EIGEN
  #REQUIRED_HEADERS  HeaderOnlyTpl_stuff.hpp
  MUST_FIND_ALL_HEADERS
)


# INCLUDE(TribitsTplDeclareLibraries)
# TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES( EIGEN
#   #REQUIRED_LIBS_NAMES 
#   MUST_FIND_ALL_HEADERS
#   )
