TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES mpl
  # LIB_OPTIONAL_PACKAGES
  #
  LIB_REQUIRED_TPLS EIGEN
  LIB_OPTIONAL_TPLS GTEST MPI TRILINOS
  #REGRESSION_EMAIL_LIST simplecxx-regressions@someurl.none
  )
