TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES core ode solvers
  LIB_OPTIONAL_PACKAGES
  #
  LIB_REQUIRED_TPLS  GTEST TRILINOS EIGEN
  LIB_OPTIONAL_TPLS  MPI
  #REGRESSION_EMAIL_LIST simplecxx-regressions@someurl.none
  )

