
#ifndef ALGEBRA_MULTI_VECTOR_DOT_VECTOR_HPP_
#define ALGEBRA_MULTI_VECTOR_DOT_VECTOR_HPP_

#include "mvec_vec/algebra_eigen_multi_vector_dot_eigen_vector.hpp"
#include "mvec_vec/algebra_epetra_multi_vector_dot_epetra_vector.hpp"
#include "mvec_vec/algebra_tpetra_multi_vector_dot_tpetra_vector.hpp"
#include "mvec_vec/algebra_tpetra_block_multi_vector_dot_tpetra_block_vector.hpp"

#endif
