
#ifndef ALGEBRA_MULTI_VECTOR_DOT_MULTI_VECTOR_HPP_
#define ALGEBRA_MULTI_VECTOR_DOT_MULTI_VECTOR_HPP_

#include "mvec_mvec/algebra_epetra_multi_vector_dot_epetra_multi_vector.hpp"
#include "mvec_mvec/algebra_tpetra_multi_vector_dot_tpetra_multi_vector.hpp"
#include "mvec_mvec/algebra_tpetra_block_multi_vector_dot_tpetra_block_multi_vector.hpp"

#endif
