TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES core
  LIB_OPTIONAL_PACKAGES
  #
  LIB_REQUIRED_TPLS  TRILINOS
  LIB_OPTIONAL_TPLS  MPI  EIGEN
  #REGRESSION_EMAIL_LIST simplecxx-regressions@someurl.none
  )

