TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES 
  LIB_OPTIONAL_PACKAGES
  #
  LIB_REQUIRED_TPLS  GTEST 
  LIB_OPTIONAL_TPLS  
  #REGRESSION_EMAIL_LIST simplecxx-regressions@someurl.none
  )
