var searchData=
[
  ['parameters_1576',['Parameters',['../classpressio_1_1optimizers_1_1Parameters.html',1,'pressio::optimizers']]],
  ['parameters_3c_20scalar_5ft_20_3e_1577',['Parameters&lt; scalar_t &gt;',['../classpressio_1_1optimizers_1_1Parameters.html',1,'pressio::optimizers']]],
  ['partialpivlu_1578',['PartialPivLU',['../structpressio_1_1solvers_1_1linear_1_1direct_1_1PartialPivLU.html',1,'pressio::solvers::linear::direct']]],
  ['potrsl_1579',['potrsL',['../structpressio_1_1solvers_1_1linear_1_1direct_1_1potrsL.html',1,'pressio::solvers::linear::direct']]],
  ['potrsu_1580',['potrsU',['../structpressio_1_1solvers_1_1linear_1_1direct_1_1potrsU.html',1,'pressio::solvers::linear::direct']]],
  ['preconditioned_1581',['Preconditioned',['../structpressio_1_1rom_1_1lspg_1_1impl_1_1Preconditioned.html',1,'pressio::rom::lspg::impl']]],
  ['preconditionedjacobianpolicy_1582',['PreconditionedJacobianPolicy',['../classpressio_1_1rom_1_1decorator_1_1PreconditionedJacobianPolicy.html',1,'pressio::rom::decorator']]],
  ['preconditionedproblemtraits_1583',['PreconditionedProblemTraits',['../structpressio_1_1rom_1_1lspg_1_1impl_1_1steady_1_1PreconditionedProblemTraits.html',1,'pressio::rom::lspg::impl::steady']]],
  ['preconditionedproblemtraitscontinuoustimeapi_1584',['PreconditionedProblemTraitsContinuousTimeApi',['../structpressio_1_1rom_1_1lspg_1_1impl_1_1unsteady_1_1PreconditionedProblemTraitsContinuousTimeApi.html',1,'pressio::rom::lspg::impl::unsteady']]],
  ['preconditionedresidualpolicy_1585',['PreconditionedResidualPolicy',['../classpressio_1_1rom_1_1decorator_1_1PreconditionedResidualPolicy.html',1,'pressio::rom::decorator']]],
  ['problemcontinuoustimeapi_1586',['ProblemContinuousTimeApi',['../structpressio_1_1rom_1_1lspg_1_1impl_1_1unsteady_1_1ProblemContinuousTimeApi.html',1,'pressio::rom::lspg::impl::unsteady::ProblemContinuousTimeApi&lt; lspg_type, stepper_tag, fom_system_type, lspg_state_type, Args &gt;'],['../classpressio_1_1rom_1_1galerkin_1_1impl_1_1ProblemContinuousTimeApi.html',1,'pressio::rom::galerkin::impl::ProblemContinuousTimeApi&lt; galerkin_type, stepper_tag, fom_system_type, rom_state_type, Args &gt;']]],
  ['problemdiscretetimeapi_1587',['ProblemDiscreteTimeApi',['../classpressio_1_1rom_1_1lspg_1_1impl_1_1unsteady_1_1ProblemDiscreteTimeApi.html',1,'pressio::rom::lspg::impl::unsteady::ProblemDiscreteTimeApi&lt; lspg_type, stepper_tag, fom_system_type, lspg_state_type, Args &gt;'],['../classpressio_1_1rom_1_1galerkin_1_1impl_1_1ProblemDiscreteTimeApi.html',1,'pressio::rom::galerkin::impl::ProblemDiscreteTimeApi&lt; galerkin_type, stepper_tag, fom_system_type, rom_state_type, rom_jacobian_type, Args &gt;']]],
  ['problemsteady_1588',['ProblemSteady',['../classpressio_1_1rom_1_1lspg_1_1impl_1_1steady_1_1ProblemSteady.html',1,'pressio::rom::lspg::impl::steady']]],
  ['publicly_5finherits_5ffrom_1589',['publicly_inherits_from',['../structpressio_1_1mpl_1_1publicly__inherits__from.html',1,'pressio::mpl']]],
  ['pydecoder_1590',['PyDecoder',['../structpressio_1_1rom_1_1impl_1_1PyDecoder.html',1,'pressio::rom::impl']]],
  ['pydecoder_3c_20_3a_3apressio_3a_3ampl_3a_3aenable_5fif_5ft_3c_20_3a_3apressio_3a_3acontainers_3a_3apredicates_3a_3ais_5fmatrix_5fwrapper_5fpybind11_3c_20matrix_5ftype_20_3e_3a_3avalue_20and_20_3a_3apressio_3a_3acontainers_3a_3apredicates_3a_3ais_5fvector_5fwrapper_5fpybind11_3c_20fom_5fstate_5ftype_20_3e_3a_3avalue_20_3e_2c_20matrix_5ftype_2c_20fom_5fstate_5ftype_20_3e_1591',['PyDecoder&lt; ::pressio::mpl::enable_if_t&lt; ::pressio::containers::predicates::is_matrix_wrapper_pybind11&lt; matrix_type &gt;::value and ::pressio::containers::predicates::is_vector_wrapper_pybind11&lt; fom_state_type &gt;::value &gt;, matrix_type, fom_state_type &gt;',['../structpressio_1_1rom_1_1impl_1_1PyDecoder_3_01_1_1pressio_1_1mpl_1_1enable__if__t_3_01_1_1pressi9f402c0177c387612aec8e598b2497d6.html',1,'pressio::rom::impl']]]
];
