# This is a basic workflow to help you get started with Actions

name: Auto Generate Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ docsUpdate ]
  pull_request:
    branches: [ docsUpdate ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - name: Install doxygen
        run: sudo apt-get install doxygen
      
      # Runs a single command using the runners shell
      - name: Install TPLs
        run: |
          sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
          sudo apt-get install dvipng
          pip install --upgrade pip
          pip install jinja2 Pygments
      - name: Clone repos
        run: |
          git clone -b docsUpdate https://github.com/Pressio/pressio.git
          git clone https://github.com/mosra/m.css.git
          ls -lh
      - name: Generate documentation
        run: |
          cd pressio/docs
          pwd
          rm -rf html/ xml/ latex/ 
          git branch 
          ls -lh .
          cd ../../m.css/documentation
          ./doxygen.py ../../pressio/docs/conf.py
          ls -lh ../../pressio/docs/html/
      # - name: Commit changes
      #   run: |
      #     pwd
      #     cd pressio/docs/
      #     ls -lh .
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add html
      #     git add xml
      #     git add latex
      #     git add .
      #     git commit -m "Generated html and xml via github action" --allow-empty  
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
      #     directory: 'pressio/'
