name: Pressio Testing

on: [push]

jobs:
  container:
      runs-on: ubuntu-latest
      container: pressiomodelreduction/ubuntu-20.04-gnu_9-eigen_3.3.7-gtest
      env:
        pressio_dir: /pressio
        target_dir: /out
        eigen_path: /usr/local/eigen
        gtest_path: /usr/local/gtest
      steps:
        - uses: actions/checkout@v2
        - run: |
            echo $(pwd)
          name: Checking path
